Prepare for April 7 security update (weekly)
jenkins-infra/release pull request #142
Opened 2021-03-31 17:54 UTC by daniel-beck

Really unsure whether this is correct, the docs do not match file contents 😞

2021-03-31 18:45 UTC, timja approved these changes

2021-04-01 00:37 UTC, MarkEWaite approved these changes

2021-04-06 07:35 UTC, olblak commented on profile.d/security
> +RELEASE_GIT_PRODUCTION_BRANCH=security-master
This variable is used to promote git content from a source to destination, you never used that as you preferred to do it manually

2021-04-06 07:36 UTC, olblak commented on profile.d/security
> -MAVEN_REPOSITORY_PRODUCTION_NAME=releases
Same here, the 'PRODUCTION' is used for promotion mechanism, which is something you do manually

2021-04-06 07:42 UTC, olblak requested changes
Current settings only cover promotion mechanisms for git and Artifactory which we always manually do

2021-04-06 07:53 UTC, olblak approved these changes

2021-04-06 07:58 UTC, olblak approved these changes

2021-04-06 07:58 UTC, merged